### PR TITLE
Python3 compatibility

### PR DESCRIPTION
**Pull request by marcogoldin**
Porting get_fb_posts to python 3. Fixed Exception, managed to have a JSON object as string, not bytes. Fixed encoding for python 3.

### CODE REVIEW

**Comment by minimaxir** [comment]
I'll need to do some testing first before pulling.

Do these changes break 2.7 compatibility? (I'm not an export on backporting). If so, it may be better to commit as a separate file.

**Comment by marcogoldin** [comment]
Ok, sure, do some tests then we'll see, thank you. Yes i think it'll breaks 2.7 compatibility, al least for the changed urrlib library in py3, but it's a separate file, i named it py3.5_get_fb_posts_fb_page.py just to be sure.

**Comment by PhanDuc** [comment]
Hi @marcogoldin ,
I check your py3.5_get_fb_post_fb_page.py. Its run ok but when i check the csv file, its had problem with column "status_message" with text is encode like this : "Bá»™ trang sá»©c dÃ nh cho bÃ© gÃ¡i yÃªu mÃ u xanh nÆ°á»›c biá»ƒn Ä‘Ã¢y ah â¤ï¸ "
Do you have any ideal how to fix that's ?
(This page i used to test : gianajewelry)

**Comment by minimaxir** [comment]
Tested it in 3.5 on my system: works great! (Yeah, it won't work in 2.7 due to missing module, that was a silly question on my part). Since the script is a separate file, that's fine.

Will update README appropriately.

@PhanDuc I saw no issues running the 3.5 version of this script on that page with the encoding fix. Note that if you are opening it up in Excel, it may get fussy.

**Comment by PhanDuc** [comment]
@minimaxir , I opened with excel and got that error but if opened in notepad++ its ok !
I don't know why but sure that script now work ok with python2x and python3x.

**Comment by marcogoldin** [comment]
Thanks @minimaxir, glad it worked fine. Anyway i'll try to dig deeper into the encoding issue, i didn't have any problem opening it in pandas or sublime or openrefine, but when it comes to bytes vs. text types python ca be fuzzy, sometimes.

**Comment by eoehri** [comment]
Could you please do the same for the get_fb_comments_from_fb.py? I'm trying it by myself right now but did not succeed so far. Thanks for the work!

**Comment by marcogoldin** [comment]
Great @eoehri! i just checked in for your comment, now i see your pull request. Actually i've been trying myself do a porting, but i think that script has some problems upstream, i've run it many times in python 2 and it keeps freezing after 30000 - 35000 comments. But it could be a facebook problem, too many request can broke even NodeXL with the facebook api. Did you test your python 3 version on a page?

**Pull request merged**
