### PR TITLE
CLI added 

### PR DESCRIPTION
**Pull request by gabru-md**
With reference to issue #45 CLI has been added to all the Python files.
`Readme.md` has also been updated with the arguments required.

### BTW: Thanks for creating this script ! <3

- gabru-md

### CODE REVIEW

**Comment by minimaxir** [comment]
Seems like a good approach for a CLI but may need a few tweaks for a consistent style:

* Can you conform to PEP8, especially with the `description` (e.g. listing with autopep8)?
* Should the `get_args()` be within scope of the `if __name__ == '__main__':` since it's from the CLI?

**Comment by gabru-md** [comment]
@minimaxir 
Okay it can be done. 
1. The code will be formatted using autoPEP8.
2. I did not notice it before, but now i'll call the `get_args()` inside `__name__ == "__main__"`.

**Comment by gabru-md** [comment]
I've done the necessary changes but if still something is missing then forgive me XD

gabru-md

**Comment by gabru-md** [comment]
@minimaxir 
what happened sir?

**Comment by minimaxir** [comment]
This PR requires additional testing since it changes how the script is operated, so it may take a little more time to merge. I'll see what I can do today.

**Comment by gabru-md** [comment]
is the testing done master?

**Comment by minimaxir** [comment]
Currently busy with other things. No ETA on when this will be merged.

**Comment by minimaxir** [comment]
Merging this into a CLI branch for the time being. The core functionality is fine, but it will need a lot of fixing up before I merge into Master.

**Pull request merged**
