### PR TITLE
Add CODE Cutting off scrape after a certain date.

### PR DESCRIPTION
**Pull request by dizwe**
I add add since, until that can cut the period that I want to scrape.
Because your time is set based on EST time, so I also did.

Somebody don't want to use this function.
So if user since=None, until=None, the work works just as you wrote.

### CODE REVIEW

**Comment by minimaxir** [comment]
No longer applicable.

**Comment by dizwe** [comment]
Does the 'No longer applicable' means either the code does not run properly OR you don't need additional since,until code to your code? If 'No longer applicable' meaning  the latter( you don't have to additional since,until code to your code), I just wondering why you commit since, until date parameter not merge my code. 
 I just want to know the specific reason you don't merge my code if you think that since/until parameter is necessary. Somehow thanks for making facebook-scraper!

**Comment by minimaxir** [comment]
Back then, code changes broke the PR.

The new code I added avoids a few bugs present in this PR (this PR does not allow the user to set just one of since/until, and this PR checks against `None` instead of checking against an empty string)

**Comment by dizwe** [comment]
Thank you for commenting! I will consider about usability when I write the code. :]

**Pull request closed without merging**
